version: '2'

services:
  server:
    container_name: freepbx_server
    image: docker.io/ovox/freepbx:17.0
    privileged: true
    ports:
      - 443:443
      - 4445:4445
      - 4569:4569/udp
      - 5060
      - 5060:5060/udp
      - 5160:5160/udp
      - 18000-18100:18000-18100/udp
    environment:
      - TZ=America/Caracas
      - DB_USER=asterisk
      - DB_PASS=asterisk
      - DBENGINE=mysql
      - DBNAME=asterisk
      - DBHOST=freepbx_mariadb
      - DBPORT=3306
      - CDRDBNAME=asteriskcdrdb
      - DBUSER=asterisk
      - DBPASS=asterisk
      - USER=asterisk
      - GROUP=asterisk
      - WEBROOT=/var/www/html
      - ASTETCDIR=/etc/asterisk
      - ASTMODDIR=/usr/lib64/asterisk/modules
      - ASTVARLIBDIR=/var/lib/asterisk
      - ASTAGIDIR=/var/lib/asterisk/agi-bin
      - ASTSPOOLDIR=/var/spool/asterisk
      - ASTRUNDIR=/var/run/asterisk
      - AMPBIN=/var/lib/asterisk/bin
      - AMPSBIN=/usr/sbin
      - AMPCGIBIN=/var/www/cgi-bin
      - AMPPLAYBACK=/var/lib/asterisk/playback
      - SSL_CERT_FILE=/etc/apache2/certs/server.crt
      - SSL_CERT_KEY_FILE=/etc/apache2/certs/server.key
    volumes:
      - ./certs:/etc/apache2/certs:ro
      - wwwvol:/var/www/html
      - varvol:/var/lib/asterisk
      - etcvol:/etc/asterisk
      - usrvol:/usr/lib64/asterisk
      - logvol:/var/log/asterisk
    restart: unless-stopped
    networks:
      asterisk:
        ipv4_address: 172.18.0.3
      macvlan0:
        ipv4_address: 192.168.1.180

  mariadb:
    container_name: freepbx_mariadb
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./datadb:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - TZ=America/Puerto_Rico
      - MYSQL_ROOT_PASSWORD=asterisk
      - MYSQL_DATABASE=asterisk
      - MYSQL_USER=asterisk
      - MYSQL_PASSWORD=asterisk
    networks:
      asterisk:
        ipv4_address: 172.18.0.2

volumes:
  varvol:
  etcvol:
  usrvol:
  wwwvol:
  logvol:

networks:
  asterisk:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
  macvlan0:
    external: true